evaluation:
  MAX_ENEMY_DENSITY: 0.15
  MAX_CANNON_DENSITY: 0.15
  MAX_PIPE_DENSITY: 0.15
  MAX_JUMP_DENSITY: 0.2
  MAX_PLATFORM_DENSITY: 0.1

  ENEMY_WEIGHT: 0.60
  CANNON_WEIGHT: 0.30
  PIPE_WEIGHT: 0.20
  JUMP_WEIGHT: 0.20
  PLATFORM_WEIGHT: 0.30

  num_patches: 10
  target_difficulty: 0.8
  temperature: 0.5
  guidance_scales: 
    - 0.0
    - 1.0
    - 2.0
    - 3.0
    - 5.0
    - 7.0
  num_samples_per_target: 5
  target_difficulties: 
    - 0.0
    - 0.2
    - 0.4
    - 0.6
    - 0.8
    - 1.0

  